nav:
  - Home: index.md
  - Usage:
    - General:
      - First Boot: usage/general/first-boot.md
      - Rebooting: usage/general/rebooting.md
      - Flashing Firmware: usage/general/flashing-firmware.md
    - Applications:
      - Power: usage/applications/power.md
  - Development:
    - Hardware:
      - Developer Board: development/hardware/devboard-stlinkV3.md

site_name: Flipper Zero â€” Documentation
site_url: https://docs.flipperzero.one/en/
edit_uri: https://github.com/Flipper-Zero/docs/edit/master/en/content/

extra:
  remark: docs-en

theme:
  language: en
